repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: experiments/|tools/
      - id: check-yaml
        exclude: experiments/|tools/
      - id: end-of-file-fixer
        exclude: experiments/|tools/
      - id: requirements-txt-fixer
        exclude: experiments/|tools/
      - id: double-quote-string-fixer
        exclude: experiments/|tools/
      - id: check-merge-conflict
        exclude: experiments/|tools/
      - id: fix-encoding-pragma
        exclude: experiments/|tools/
        args: ["--remove"]
      - id: mixed-line-ending
        exclude: experiments/|tools/
        args: ["--fix=lf"]

  - repo: https://github.com/PyCQA/isort.git
    rev: 5.11.5
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: configs/|examples/|experiments/|tools/|tests/
        additional_dependencies: [flake8-docstrings]
